### ISSUE TITLE
Wikiの表記統一

### ISSUE THREAD

**Issue by kanta** [kanta/STEP400_prototype#1]
# ページ全体の見出しは#が1個
### コマンド自体は#が3個

コマンドは```これ（`が3個）```を`これ（`が1個）`に変更する

「返答」という文言は、block code から出す

返答の説明部分、メッセージの文字はblock code（`が1個）でくくる

**Comment by yuskid** [comment]
正：block code（`が3個）でくくる

**Comment by yuskid** [comment]
手順メモ
1. 「##」で検索、「###」に置換（「###」を置換しない）
1-2. 「#」で検索、「##」に置換（「##」「###」を置換しない）
2. 「```」で検索、適切な部分（単語/文節）を「`」に置換（返答、メッセージ部を置換しない）
3. 返答、メッセージ部分をチェックし、「```」でくくる
4. 改行チェック、エラーチェック

**Comment by kanta** [comment]
@yuskid すみません、コマンドによっては中見出しがないものがありましたね、、
例えば
https://github.com/kanta/STEP400_prototype/wiki/%E8%A8%AD%E5%AE%9A%E3%83%BB%E3%83%A6%E3%83%BC%E3%83%86%E3%82%A3%E3%83%AA%E3%83%86%E3%82%A3
このページのように
- コマンドは＃が3個に統一
- ＃が2個の見出しがなくてもコマンドは＃が3個
- コマンドや返答のメッセージに続くリスト表示の中で、メッセージ内の変数を説明していますが、その変数名に当たるところは「‘」でくくりたい。↓このような感じです。
![image](https://user-images.githubusercontent.com/1097902/90872783-1a2fc200-e3d8-11ea-9450-12444bdae186.png)

という風に修正作業をお願いできますか？結構大きな修正になると思いますが。。

**Comment by kanta** [comment]
@yuskid あとWordPressのほうはやっぱりサイト内リンク使えないみたいです。お手数ですがリンク部分は普通にURLを書く方式でお願いします！

**Comment by kanta** [comment]
初期値のリスト
https://docs.google.com/spreadsheets/d/1EAUpzARE69ip6_LolZAv3crpmXGsESjCOz6EqVY1lUo/edit#gid=0

**Comment by kanta** [comment]
旧フォーマット
https://github.com/kanta/STEP400_prototype/wiki/%E8%A8%AD%E5%AE%9A%E3%83%BB%E3%83%A6%E3%83%BC%E3%83%86%E3%82%A3%E3%83%AA%E3%83%86%E3%82%A3_old

新フォーマット
https://github.com/kanta/STEP400_prototype/wiki/%E8%A8%AD%E5%AE%9A%E3%83%BB%E3%83%A6%E3%83%BC%E3%83%86%E3%82%A3%E3%83%AA%E3%83%86%E3%82%A3

**Comment by kanta** [comment]
### `/setDestIp`
#### アーギュメント
なし

#### 実行可能タイミング
常時

#### 説明
モータの状態に変化があったときに通知するメッセージや、問い合わせへ返答するメッセージなどの送り先IPアドレス(`destIp`)を指定します。このメッセージを送信したIPアドレスを`destIp`に設定します。

また、`destIp`が設定されるまでは、STEP400からOSCメッセージの送信は行いませんので、一番最初にこのコマンドを送信してください。

#### 返答

```
/destIp (int)destIp[0] (int)destIp[1] (int)destIp[2] (int)destIp[3] (bool)isNewDestIp
```
| アーギュメント | 範囲 | 説明 |
| --- | --- | --- |
| destIp[0-3] | 0-255| destIpの各桁 |
| isNewDestIp | 0-1 | destIpが変更されたかどうかを示します。変更されていると1, すでに同じアドレスが設定されていた場合は0 |

#### 初期値
10.0.0.10

**Comment by yuskid** [comment]
・見出し追加（アーギュメント、実行可能タイミング、説明、返答、初期値）
・リスト→表にする（箇条書き部分）

**Comment by kanta** [comment]
(bool) enable
1で有効, 0で無効
範囲 0-1
